apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/host
  - ../../base/member
  - ../../base/all-clusters
  - ../../cluster-config/staging
components:
  - ../../k-components/host-on-local-cluster
  - ../../k-components/spi-inject-component-source-path
