apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/host
  - ../../base/member
  - ../../base/all-clusters
  - ../../base/tekton-ci
components:
  - ../../k-components/host-on-local-cluster
