apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=ef39c51d2952c724950e4187f473582455603bee
- ../../openshift-gitops/overlays/production-and-dev
- ../../base/external-secrets
- ../../base/monitoring
- authentication

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: ef39c51d2952c724950e4187f473582455603bee

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
