apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/local-dev-env-with-k8s-db?ref=6963dac78dbea949f9218e448c053fdde84759e5
- ../openshift-gitops


images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 6963dac78dbea949f9218e448c053fdde84759e5

