apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  webhook:
    image:
      repository: quay.io/redhat-appstudio/external-secrets
      tag: 1fdb2d579e93acad4eb8394c535b5d1b7c8acbad 
  certController:
    image:
      repository: quay.io/redhat-appstudio/external-secrets
      tag: 1fdb2d579e93acad4eb8394c535b5d1b7c8acbad 
  image:
    repository: quay.io/redhat-appstudio/external-secrets
    tag: 1fdb2d579e93acad4eb8394c535b5d1b7c8acbad 
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
   requests:
     cpu: 10m
     memory: 96Mi
   limits:
     cpu: 100m
     memory: 256Mi
