apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/redhat-appstudio/build-service/config/default?ref=96ebfbd3a5c87912697ec5021b677e9405c2276c

namespace: build-service

images:
- name: quay.io/redhat-appstudio/build-service
  newName: quay.io/redhat-appstudio/build-service
  newTag: 96ebfbd3a5c87912697ec5021b677e9405c2276c

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: image-expiration-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: pac-webhook-insecure-ssl-patch.yaml

components:
  - ../components/rh-certs
