apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            appstudio.redhat.com/create-cluster-config: "true"
  template:
    metadata:
      name: cluster-config-{{nameNormalized}}
    spec:
      project: default
      source:
        path: cluster-config/staging/{{nameNormalized}}
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: cluster-config
        server: '{{server}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
