apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/host
  - ../../base/host/optional/infra-deployments/dev-sso
  - ../../base/member
  - ../../base/all-clusters
patchesStrategicMerge:
  - delete-applications.yaml
components:
  - ../../k-components/all-in-one
namespace: openshift-gitops
patches:
  - path: development-overlay-patch.yaml
    target:
      kind: ApplicationSet
      version: v1alpha1
      name: gitops
  - path: development-overlay-patch.yaml
    target:
      kind: ApplicationSet
      version: v1alpha1
      name: pipeline-service
  - path: development-overlay-patch.yaml
    target:
      kind: ApplicationSet
      version: v1alpha1
      name: build-service
