kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-admin
  namespace: spi-system
rules:
  - verbs:
      - get
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - get
      - delete
      - create
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-admin
  namespace: spi-system
subjects:
  - kind: User
    name: skabashnyuk
  - kind: User
    name: sparkoo
  - kind: User
    name: metlos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-admin
